Transito\LoginBundle\Validations\Login:
    properties:
        username:
            - NotBlank:
                message: "El nombre de usuario no puede estar vacio"
        password:
            - NotBlank:
                message: "La contraseña no puede estar vacia"