Transito\LoginBundle\Validations\Login:
    properties:
        username:
            - NotBlank:
                message: "El nombre de usuario no puede estar vacio"
        password:
            - NotBlank:
                message: "La contrase침a no puede estar vacia"
Transito\MainBundle\Validations\Pau:
    properties:
        name:
            - NotBlank:
                message: "El nombre no puede estar vacio"
        location:
            - NotBlank:
                message: "La direcci칩n no puede estar vacia"
        email:
            - NotBlank:
                message: "El correo electronico no puede estar vacio"
            - Email:
                message: El correo electronico "{{ value }}" no es valid칩
                checkMX: true
        operation:
            - NotBlank:
                message: "El horario de atenci칩n no puede estar vacio"
            - Regex:
                pattern: '/^([1-9]|1[0-2]) (am|pm) - ([1-9]|1[0-2]) (am|pm)$/'
                message: "El formato de hora es invalido"