Transito\LoginBundle\Validations\Login:
    properties:
        username:
            - NotBlank:
                message: "El nombre de usuario no puede estar vacio"
        password:
            - NotBlank:
                message: "La contraseña no puede estar vacia"
Transito\MainBundle\Validations\Pau:
    properties:
        name:
            - NotBlank:
                message: "El nombre no puede estar vacio"
        location:
            - NotBlank:
                message: "La dirección no puede estar vacia"
        email:
            - NotBlank:
                message: "El correo electronico no puede estar vacio"
            - Email:
                message: El correo electronico "{{ value }}" no es validó
                checkMX: true
        operation:
            - NotBlank:
                message: "El horario de atención no puede estar vacio"
            - Regex:
                pattern: '/^([1-9]|1[0-2]) (am|pm) - ([1-9]|1[0-2]) (am|pm)$/'
                message: "El formato de hora es invalido"
Transito\MainBundle\Validations\Client:
    properties:
        dni:
            - NotBlank:
                message: "El dni no puede estar vacio"
            - Regex:
                pattern: '/^\d+$/'
                message: "El formato del dni es invalido"
        firstName:
            - NotBlank:
                message: "El primer nombre no puede estar vacio"
            - Regex:
                pattern: '/^\w+$/'
                message: "El formato del primer nombre es invalido"
        lastName:
            - NotBlank:
                message: "El segundo nombre no puede estar vacio"
            - Regex:
                pattern: '/^\w+$/'
                message: "El formato del segundo nombre es invalido"
        firstSurname:
            - NotBlank:
                message: "El primer apellido no puede estar vacio"
            - Regex:
                pattern: '/^\w+$/'
                message: "El formato del primer apellido es invalido"
        lastSurname:
            - NotBlank:
                message: "El segundo apellido no puede estar vacio"
            - Regex:
                pattern: '/^\w+$/'
                message: "El formato del segundo apellido es invalido"
        birthday:
            - NotBlank:
                message: "La fecha de nacimiento no puede estar vacia"
            - Regex:
                pattern: '/^([0]?[1-9]|[1|2][0-9]|[3][0|1])-([0]?[1-9]|[1][0-2])-(19[0-9]{2}|[2-9][0-9]{3})$/'
                message: "El formato de la fecha es invalido"
        location:
            - NotBlank:
                message: "La dirección no puede estar vacia"
        phone:
            - NotBlank:
                message: "El telefono no puede estar vacio"
            - Regex:
                pattern: '/^\(([1-2]|[4-8])\)-[0-9]{7}$/'
                message: "El formato de telefono es invalido"
        cellphone:
            - NotBlank:
                message: "El celular no puede estar vacio"
            - Regex:
                pattern: '/^(3[0-9]{2})-[0-9]{3}-[0-9]{4}$/'
                message: "El formato de celular es invalido"
        email:
            - NotBlank:
                message: "El correo electronico no puede estar vacio"
            - Email:
                message: El correo electronico "{{ value }}" no es validó
                checkMX: true
        payment:
            - NotBlank:
                message: "El pago no puede estar vacio"
            - Regex:
                pattern: '/^\d+$/'
                message: "El formato de pago es invalido"
Transito\MainBundle\Validations\Procedure:
    properties:
        date:
            - NotBlank:
                message: "La fecha no puede estar vacia"
            - Regex:
                pattern: '/^([0]?[1-9]|[1|2][0-9]|[3][0|1])-([0]?[1-9]|[1][0-2])-(19[0-9]{2}|[2-9][0-9]{3})$/'
                message: "El formato de la fecha es invalido"
        dni:
            - NotBlank:
                message: "El dni no puede estar vacio"
            - Regex:
                pattern: '/^\d+$/'
                message: "El formato del dni es invalido"
        name:
            - NotBlank:
                message: "El nombre no puede estar vacio"